"""S8: assemble the (post-critique) paper-ready summary into notes/RESULTS.md.

Thin renderer over the authoritative artifacts (run these first):
  python -m scripts.analysis --match-scale       -> outputs/results/analysis.json
  python -m scripts.calibration_analysis         -> outputs/results/calibration.json

Reports compute saving with matched stopping mechanics + bootstrap 95% CIs + oracle/random
yardsticks (see CRITIQUE_LOG). Does NOT recompute savings the old (mechanism-confounded) way.
"""
import json
import os

from src import config
from src.logutil import log

MODEL_ORDER = {"qwen-0.5b": 0, "qwen-1.5b": 1, "qwen-7b": 2, "llama-8b": 3}


def _fmt(d):
    if not d or d.get("saving") is None:
        return "n.r."
    lo, hi = d.get("ci95", [None, None])
    if lo is None:
        return f"{d['saving']:.3f}"
    return f"{d['saving']:.3f} [{lo:.3f},{hi:.3f}]"


def _cell_key(name):
    ds, _, model = name.partition("_")
    return (ds, MODEL_ORDER.get(model, 9))


def main():
    config.ensure_dirs()
    apath = os.path.join(config.RESULTS_DIR, "analysis.json")
    if not os.path.exists(apath):
        raise SystemExit("run `python -m scripts.analysis --match-scale` first")
    A = json.load(open(apath))
    cfg = A["config"]

    L = ["# Results (auto-generated by scripts.make_report) — PRIVATE", "",
         f"Config: k0={cfg['k0']} (2-stage), min_k={cfg['min_k']} (incremental), "
         f"bootstrap B={cfg['B']}, iso-accuracy tol={cfg['tol']}. "
         "Saving = 1 − mean_cost/K at the cheapest operating point within tol of full-budget "
         "accuracy; [.,.] = percentile 95% CI over problems (selection bootstrapped).", "",
         "**Mechanism note:** `agreement@k0` and `trained@k0` share the 2-stage ceiling "
         "1−k0/K; `confidence`/`esc` are incremental (ceiling 1−min_k/K). We compare signals only "
         "within the matched (2-stage) group; incremental methods are a separate group.", ""]

    # --- head-to-head (matched 2-stage) + incremental + yardsticks ---
    L += ["## Compute saving (matched mechanics + 95% CI + yardsticks)", "",
          "Oracle shown as consistency/achievability: **consistency** = correct iso-accuracy ceiling "
          "for our metric (stop when plurality==full-budget answer); **achievability** = stop at "
          "earliest *correct* plurality (targets higher accuracy, not the same iso-accuracy point — "
          "so on weak models it can be *lower* saving but higher accuracy). `n.r.` = the operating "
          "point does not exist (no threshold reaches iso-accuracy).", "",
          "| dataset | model | n | full_acc | agree@k0 | trained@k0 | conf(inc) | esc(inc) | "
          "oracle cons/ach | random |", "|---|---|--:|--:|---|---|---|---|---|--:|"]
    for name in sorted(A["cells"], key=_cell_key):
        c = A["cells"][name]
        ds, _, model = name.partition("_")
        h, inc = c["head_to_head_2stage"], c["incremental"]
        r = c["random_stop"]["saving_at_iso_acc"]
        orc = f"{c['oracle_consistency']['saving']:.2f}/{c['oracle_achievable']['saving']:.2f}"
        L.append(f"| {ds} | {model} | {c['n']} | {c['full_acc']} | {_fmt(h.get('agreement'))} | "
                 f"{_fmt(h.get('trained'))} | {_fmt(inc.get('confidence'))} | {_fmt(inc.get('esc'))} | "
                 f"{orc} | {'n.r.' if r is None else f'{r:.3f}'} |")

    # --- paired difference (trained - agreement) + TOST + MDE ---
    L += ["", "## Signal comparison: paired Δ (trained − agreement) on the same problems", "",
          "Paired bootstrap (shared resample indices), TOST equivalence @ margin ±0.05, and the "
          "achieved minimum-detectable-effect (MDE = ½·95%-CI width). `censored` = a signal is pinned "
          "at the 2-stage ceiling (comparison uninformative).", "",
          "| dataset | model | Δ | 95% CI | TOST | MDE | censored |",
          "|---|---|--:|---|---|--:|:--:|"]
    for name in sorted(A["cells"], key=_cell_key):
        pd = A["cells"][name].get("paired_trained_minus_agreement")
        if not pd or pd.get("delta") is None:
            continue
        ds, _, model = name.partition("_")
        lo, hi = pd["ci95"]
        L.append(f"| {ds} | {model} | {pd['delta']:+.3f} | [{lo:+.3f},{hi:+.3f}] | {pd['tost']} | "
                 f"{pd['mde']:.3f} | {'yes' if pd.get('censored') else 'no'} |")

    # --- subset-matched scale (fix #3) ---
    if "scale_matched" in A:
        sm = A["scale_matched"]
        L += ["", f"## Scale on the 7B-matched GSM8K subset (n={sm['n_ids']} shared ids)", "",
              "Removes the sample-size/subset confound in the scale story (precision confound — 7B "
              "is 4-bit — remains; needs a GPU fp16 run).", "",
              "| model | full_acc | agree@k0 | trained@k0 | conf(inc) | oracle | random |",
              "|---|--:|---|---|---|---|--:|"]
        for model in sorted(sm["cells"], key=lambda m: MODEL_ORDER.get(m, 9)):
            c = sm["cells"][model]
            h, inc = c["head_to_head_2stage"], c["incremental"]
            r = c["random_stop"]["saving_at_iso_acc"]
            L.append(f"| {model} | {c['full_acc']} | {_fmt(h.get('agreement'))} | "
                     f"{_fmt(h.get('trained'))} | {_fmt(inc.get('confidence'))} | {_fmt(c['oracle'])} | "
                     f"{'n.r.' if r is None else f'{r:.3f}'} |")

    # --- calibration table ---
    cpath = os.path.join(config.RESULTS_DIR, "calibration.json")
    if os.path.exists(cpath):
        calib = json.load(open(cpath))
        kmax_c = max(c["k"] for c in calib)
        calib = [r for r in calib if r["k"] == kmax_c]
        calib.sort(key=lambda r: (r["dataset"], MODEL_ORDER.get(r["model"], 9)))
        L += ["", f"## Calibration of the agreement signal (ECE, K={kmax_c})", "",
              "Raw ECE [95% CI], bin robustness (5/10/15), the identity check "
              "ratio=ECE/|mean_conf−acc| (≈1 ⇒ ECE is just aggregate bias, ~no resolution content), "
              "and ECE after a monotone isotonic recalibration (2-fold cross-fit). "
              "isotonic≈0 ⇒ a single monotone map removes the 'miscalibration' ⇒ the raw ECE reflects "
              "that plurality share is not a probability, not a resolution failure.", "",
              "| dataset | model | mean_conf | acc | ECE [95% CI] | bins 5/10/15 | ratio | "
              "ECE isotonic | ECE(T) | T |",
              "|---|---|--:|--:|---|---|--:|--:|--:|--:|"]
        for r in calib:
            lo, hi = r["ece_raw_ci95"]
            eb = r["ece_by_bins"]
            L.append(f"| {r['dataset']} | {r['model']} | {r['mean_confidence']:.3f} | "
                     f"{r['accuracy']:.3f} | {r['ece_raw']:.3f} [{lo:.3f},{hi:.3f}] | "
                     f"{eb['5']}/{eb['10']}/{eb['15']} | {r.get('ece_over_gap','—')} | "
                     f"{r.get('ece_isotonic','—')} | {r['ece_scaled']:.3f} | "
                     f"{r['temperature']:.2f} |")

    L += ["", "Notes: GSM8K + BBH grading reliable; MATH-500 grading approximate (lower bound), but "
          "cross-method comparison at fixed grading is valid. Wide CIs on low-accuracy cells reflect "
          "instability of the iso-accuracy metric when full-budget accuracy is low."]

    out = os.path.join(config.REPO_ROOT, "notes", "RESULTS.md")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    log(f"make_report DONE -> {out}")
    print("\n".join(L))


if __name__ == "__main__":
    main()
