"""S8: assemble all rollouts into a paper-ready markdown summary (private notes/RESULTS.md).

For every rollouts file: full-budget accuracy + each method's compute saving at <=1pp below full.
Also a scale view (GSM8K across model sizes). Run after pulling/regrading rollouts.

Run:
  python -m scripts.make_report
"""
import glob
import json
import os

from src import config, eval as ev
from src.logutil import log

METHODS = ["esc", "adaptive-confidence", "adaptive-agreement", "adaptive-trained"]
MODEL_ORDER = {"qwen-0.5b": 0, "qwen-1.5b": 1, "qwen-7b": 2, "llama-8b": 3}


def saving(rows, method, kmax, gate_model=None, k0=4, tol=0.01):
    full = ev.fixed_budget(rows, kmax)["accuracy"]
    pts = ev.baselines_and_adaptive(rows, k0=k0, kmax=kmax)
    if gate_model is not None:
        pts += ev.trained_gate_sweep(rows, gate_model, k0=k0, kmax=kmax)
    cand = [p for p in pts if p["policy"] == method and p["accuracy"] >= full - tol]
    if not cand:
        return None
    return round(1 - min(p["mean_cost"] for p in cand) / kmax, 3)


def parse_name(fn):
    base = os.path.splitext(os.path.basename(fn))[0]  # dataset_model
    for m in MODEL_ORDER:
        if base.endswith(m):
            return base[: -(len(m) + 1)], m
    return base, "?"


def main():
    config.ensure_dirs()
    files = sorted(glob.glob(os.path.join(config.ROLLOUTS_DIR, "*.jsonl")))
    log(f"make_report START: {len(files)} rollout file(s) under {config.ROLLOUTS_DIR}")
    rows_by = {}
    table = []
    for fi, f in enumerate(files, 1):
        ds, model = parse_name(f)
        log(f"[{fi}/{len(files)}] {os.path.basename(f)}: loading + computing savings ...")
        rows = ev.load_rollouts(f)
        kmax = len(rows[0]["samples"])
        full = ev.fixed_budget(rows, kmax)["accuracy"]
        rec = {"dataset": ds, "model": model, "n": len(rows), "kmax": kmax,
               "full_acc": round(full, 3)}
        # load the in-distribution gate if one exists for this (dataset, model)
        gate_model = None
        gp = os.path.join(config.GATE_DIR, f"{ds}_{model}.joblib")
        if os.path.exists(gp):
            from src import gate as gatemod
            gate_model = gatemod.TrainedGate.load(gp)
        for m in METHODS:
            rec[m] = saving(rows, m, kmax, gate_model=gate_model)
        log(f"[{fi}/{len(files)}] {ds}/{model}: n={len(rows)} kmax={kmax} "
            f"full_acc={rec['full_acc']} gate={'yes' if gate_model else 'no'}")
        table.append(rec)
        rows_by[(ds, model)] = rows

    table.sort(key=lambda r: (r["dataset"], MODEL_ORDER.get(r["model"], 9)))

    lines = ["# Results (auto-generated by scripts.make_report) — PRIVATE", ""]
    lines.append("Compute *saving* = 1 - mean_cost/kmax at the cheapest point within 1pp of full-budget accuracy.")
    lines.append("")
    lines.append("| dataset | model | n | kmax | full_acc | esc | confidence | agreement | trained |")
    lines.append("|---|---|--:|--:|--:|--:|--:|--:|--:|")
    for r in table:
        lines.append("| {dataset} | {model} | {n} | {kmax} | {full_acc} | {esc} | "
                     "{adaptive-confidence} | {adaptive-agreement} | {adaptive-trained} |".format(**r))
    lines.append("")
    lines.append("Notes: GSM8K + BBH grading is reliable; MATH-500 grading is approximate "
                 "(string/boxed match) — treat MATH accuracy as a lower bound, but cross-method "
                 "comparison at fixed grading is still valid.")

    out = os.path.join(config.REPO_ROOT, "notes", "RESULTS.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    log(f"make_report DONE report -> {out} ({len(table)} rows)")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
