"""S8: assemble the (post-critique) paper-ready summary into notes/RESULTS.md.

Thin renderer over the authoritative artifacts (run these first):
  python -m scripts.analysis --match-scale       -> outputs/results/analysis.json
  python -m scripts.calibration_analysis         -> outputs/results/calibration.json

Reports compute saving with matched stopping mechanics + bootstrap 95% CIs + oracle/random
yardsticks (see CRITIQUE_LOG). Does NOT recompute savings the old (mechanism-confounded) way.
"""
import json
import os

from src import config
from src.logutil import log

MODEL_ORDER = {"qwen-0.5b": 0, "qwen-1.5b": 1, "qwen-7b": 2, "llama-8b": 3}


def _fmt(d):
    if not d or d.get("saving") is None:
        return "n.r."
    lo, hi = d.get("ci95", [None, None])
    if lo is None:
        return f"{d['saving']:.3f}"
    return f"{d['saving']:.3f} [{lo:.3f},{hi:.3f}]"


def _cell_key(name):
    ds, _, model = name.partition("_")
    return (ds, MODEL_ORDER.get(model, 9))


def main():
    config.ensure_dirs()
    apath = os.path.join(config.RESULTS_DIR, "analysis.json")
    if not os.path.exists(apath):
        raise SystemExit("run `python -m scripts.analysis --match-scale` first")
    A = json.load(open(apath))
    cfg = A["config"]

    L = ["# Results (auto-generated by scripts.make_report) — PRIVATE", "",
         f"Config: k0={cfg['k0']} (2-stage), min_k={cfg['min_k']} (incremental), "
         f"bootstrap B={cfg['B']}, iso-accuracy tol={cfg['tol']}. "
         "Saving = 1 − mean_cost/K at the cheapest operating point within tol of full-budget "
         "accuracy; [.,.] = percentile 95% CI over problems (selection bootstrapped).", "",
         "**Mechanism note:** `agreement@k0` and `trained@k0` share the 2-stage ceiling "
         "1−k0/K; `confidence`/`esc` are incremental (ceiling 1−min_k/K). We compare signals only "
         "within the matched (2-stage) group; incremental methods are a separate group.", ""]

    # --- head-to-head (matched 2-stage) + incremental + yardsticks ---
    L += ["## Compute saving (matched mechanics + 95% CI + yardsticks)", "",
          "| dataset | model | n | full_acc | agree@k0 | trained@k0 | conf(inc) | esc(inc) | "
          "oracle | random |", "|---|---|--:|--:|---|---|---|---|---|--:|"]
    for name in sorted(A["cells"], key=_cell_key):
        c = A["cells"][name]
        ds, _, model = name.partition("_")
        h, inc = c["head_to_head_2stage"], c["incremental"]
        r = c["random_stop"]["saving_at_iso_acc"]
        L.append(f"| {ds} | {model} | {c['n']} | {c['full_acc']} | {_fmt(h.get('agreement'))} | "
                 f"{_fmt(h.get('trained'))} | {_fmt(inc.get('confidence'))} | {_fmt(inc.get('esc'))} | "
                 f"{_fmt(c['oracle'])} | {'n.r.' if r is None else f'{r:.3f}'} |")

    # --- subset-matched scale (fix #3) ---
    if "scale_matched" in A:
        sm = A["scale_matched"]
        L += ["", f"## Scale on the 7B-matched GSM8K subset (n={sm['n_ids']} shared ids)", "",
              "Removes the sample-size/subset confound in the scale story (precision confound — 7B "
              "is 4-bit — remains; needs a GPU fp16 run).", "",
              "| model | full_acc | agree@k0 | trained@k0 | conf(inc) | oracle | random |",
              "|---|--:|---|---|---|---|--:|"]
        for model in sorted(sm["cells"], key=lambda m: MODEL_ORDER.get(m, 9)):
            c = sm["cells"][model]
            h, inc = c["head_to_head_2stage"], c["incremental"]
            r = c["random_stop"]["saving_at_iso_acc"]
            L.append(f"| {model} | {c['full_acc']} | {_fmt(h.get('agreement'))} | "
                     f"{_fmt(h.get('trained'))} | {_fmt(inc.get('confidence'))} | {_fmt(c['oracle'])} | "
                     f"{'n.r.' if r is None else f'{r:.3f}'} |")

    # --- calibration table ---
    cpath = os.path.join(config.RESULTS_DIR, "calibration.json")
    if os.path.exists(cpath):
        calib = json.load(open(cpath))
        kmax_c = max(c["k"] for c in calib)
        calib = [r for r in calib if r["k"] == kmax_c]
        calib.sort(key=lambda r: (r["dataset"], MODEL_ORDER.get(r["model"], 9)))
        L += ["", f"## Calibration of the agreement signal (ECE, K={kmax_c})", "",
              "Raw ECE with 95% CI + bin-count robustness (5/10/15) + temperature-scaled ECE "
              "(`scripts.calibration_analysis`).", "",
              "| dataset | model | mean_conf | acc | ECE [95% CI] | ECE 5/10/15 | ECE(T) | T |",
              "|---|---|--:|--:|---|---|--:|--:|"]
        for r in calib:
            lo, hi = r["ece_raw_ci95"]
            eb = r["ece_by_bins"]
            L.append(f"| {r['dataset']} | {r['model']} | {r['mean_confidence']:.3f} | "
                     f"{r['accuracy']:.3f} | {r['ece_raw']:.3f} [{lo:.3f},{hi:.3f}] | "
                     f"{eb['5']}/{eb['10']}/{eb['15']} | {r['ece_scaled']:.3f} | "
                     f"{r['temperature']:.2f} |")

    L += ["", "Notes: GSM8K + BBH grading reliable; MATH-500 grading approximate (lower bound), but "
          "cross-method comparison at fixed grading is valid. Wide CIs on low-accuracy cells reflect "
          "instability of the iso-accuracy metric when full-budget accuracy is low."]

    out = os.path.join(config.REPO_ROOT, "notes", "RESULTS.md")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    log(f"make_report DONE -> {out}")
    print("\n".join(L))


if __name__ == "__main__":
    main()
